name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.4'
      - name: Set up msys2
        uses: msys2/setup-msys2@v2
        with:
          install: make tar zip unzip
          path-type: inherit
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: msys2 ./ci-release.sh
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            dist/
            !dist/*/*
